# Baseado na imagem Node.js
FROM node:18-alpine

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos package.json e package-lock.json
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar todo o código do projeto
COPY . .

# Expor a porta usada pelo Vite
EXPOSE 3000

# Comando para rodar o servidor de desenvolvimento do Vite
CMD ["npm", "run", "dev"]
